#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
    entities:
        - App\Entity\Destination
        - App\Entity\User
        - App\Entity\Commentaire
        - App\Entity\Trajet
        - App\Entity\Reservation

