#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\TrajetController::index


# Routes trajets

trajet.liste:
    path: /trajet/liste
    controller : App\Controller\TrajetController::liste

trajet.detail:
    path: /trajet/detail/{id}
    controller : App\Controller\TrajetController::detail

# Routes réservations
