#index:
#    path: /
#    controller: App\Controller\DefaultController::index

base:
    path: /
    defaults:
        _controller: App\Controller\TrajetController::index
        permanent: true

index:
    path: /{_locale}
    controller: App\Controller\TrajetController::index
    requirements:
        _locale: en|fr
        
# Routes trajets

trajet.liste:
    path: /{_locale}/trajet/liste
    controller: App\Controller\TrajetController::liste
    requirements:
        _locale: en|fr

trajet.detail:
    path: /{_locale}/trajet/detail/{id}
    controller: App\Controller\TrajetController::detail
    requirements:
        _locale: en|fr

trajet.self:
    path: /{_locale}/trajet/self
    controller: App\Controller\TrajetController::listeUser
    requirements:
        _locale: en|fr

trajet.ajout:
    path: /{_locale}/trajet/ajout
    controller: App\Controller\TrajetController::ajout
    requirements:
        _locale: en|fr

trajet.supprimer:
    path: /{_locale}/trajet/supprimer/{id}
    controller: App\Controller\TrajetController::supprimer
    requirements:
        _locale: en|fr

# Routes réservations

reservation:
    path: /{_locale}/reservation
    controller: App\Controller\ReservationController::index
    requirements:
        _locale: en|fr

reservation.ajout:
    path: /{_locale}/reservation/ajout/{trajetid}
    controller: App\Controller\ReservationController::ajout
    requirements:
        _locale: en|fr

reservation.supprimer:
    path: /{_locale}/reservation/supprimer/{id}
    controller: App\Controller\ReservationController::supprimer
    requirements:
        _locale: en|fr

reservation.payer:
    path: /{_locale}/reservation/payer/{id}
    controller: App\Controller\ReservationController::payer
    requirements:
        _locale: en|fr

# Routes commentaires

commentaire.ajout:
    path: /{_locale}/commentaire/ajout/{trajetid}
    controller: App\Controller\CommentaireController::ajout
    requirements:
        _locale: en|fr

commentaire.supprimer:
    path: /{_locale}/commentaire/supprimer/{id}
    controller: App\Controller\CommentaireController::supprimer
    requirements:
        _locale: en|fr

commentaire:
    path: /{_locale}/commentaire
    controller: App\Controller\CommentaireController::listeUser
    requirements:
        _locale: en|fr

# Routes user

register:
    path: /{_locale}/register
    controller: App\Controller\UserController::register
    requirements:
        _locale: en|fr

profil:
    path: /{_locale}/profil/{id}
    controller: App\Controller\UserController::profil
    requirements:
        _locale: en|fr

profil.self:
    path: /{_locale}/profil
    controller: App\Controller\UserController::self
    requirements:
        _locale: en|fr


theme:
    path: /theme/{theme}        
    controller: App\Controller\UserController::theme
    requirements:
        theme: dark|light

# Routes admin

admin:
    path: /admin
    controller: App\Controller\AdminController::index
