#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\TrajetController::index


# Routes trajets

trajet.liste:
    path: /trajet/liste
    controller : App\Controller\TrajetController::liste

trajet.detail:
    path: /trajet/detail/{id}
    controller : App\Controller\TrajetController::detail

trajet.self:
    path: /trajet/self
    controller : App\Controller\TrajetController::listeUser

trajet.ajout:
    path: /trajet/ajout
    controller : App\Controller\TrajetController::ajout

trajet.supprimer:
    path: /trajet/supprimer/{id}
    controller : App\Controller\TrajetController::supprimer


# Routes réservations
